import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { 
  Heart, 
  MapPin, 
  Sparkles, 
  Check, 
  Layers,
  ArrowUpRight
} from 'lucide-react';
import { Accommodation, RecommendationResult } from '../../types';
import { EcoScoreBadge } from '../sustainability/EcoScoreBadge';
import { useWishlist } from '../../context/WishlistContext';
import { useCompare } from '../../context/CompareContext';

interface AccommodationCardProps {
  accommodation: Accommodation;
  recommendation?: RecommendationResult;
}

export const AccommodationCard: React.FC<AccommodationCardProps> = ({
  accommodation,
  recommendation
}) => {
  const { isWishlisted, toggleWishlist } = useWishlist();
  const { addToCompare, removeFromCompare, isCompared } = useCompare();
  const [isHeartPopping, setIsHeartPopping] = useState(false);

  const isSaved = isWishlisted(accommodation.id);
  const compared = isCompared(accommodation.id);

  const handleCompareToggle = (e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    if (compared) {
      removeFromCompare(accommodation.id);
    } else {
      addToCompare(accommodation);
    }
  };

  const handleWishlistToggle = (e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setIsHeartPopping(true);
    setTimeout(() => setIsHeartPopping(false), 350);
    toggleWishlist(accommodation.id);
  };

  const propertyTypeLabels: Record<string, string> = {
    eco_lodge: 'Eco Lodge',
    glamping: 'Eco Glamping',
    boutique_hotel: 'Green Boutique Hotel',
    treehouse: 'Canopy Treehouse',
    cabin: 'Solar Earth-Cabin',
    villa: 'Permaculture Estate Villa'
  };

  return (
    <motion.div 
      initial={{ opacity: 0, y: 16 }}
      animate={{ opacity: 1, y: 0 }}
      whileHover={{ y: -5 }}
      transition={{ duration: 0.35, ease: [0.22, 1, 0.36, 1] }}
      className="bg-white rounded-3xl overflow-hidden border border-slate-200/80 shadow-xs hover:shadow-eco-md transition-shadow duration-300 flex flex-col group relative"
    >
      
      {/* Image Thumbnail & Overlays */}
      <div className="relative aspect-16/10 overflow-hidden bg-slate-100">
        <img
          src={accommodation.images[0] || 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80'}
          alt={accommodation.name}
          className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-600 ease-out"
          loading="lazy"
        />

        {/* Subtle Dark Gradient for Contrast */}
        <div className="absolute inset-0 bg-gradient-to-t from-slate-900/60 via-transparent to-black/20 pointer-events-none" />

        {/* Top Badges */}
        <div className="absolute top-3 left-3 right-3 flex items-center justify-between pointer-events-none">
          {/* Property Type Badge */}
          <span className="bg-slate-900/80 backdrop-blur-md text-white text-[10px] font-bold px-3 py-1 rounded-full pointer-events-auto border border-white/10 shadow-sm">
            {propertyTypeLabels[accommodation.property_type] || accommodation.property_type}
          </span>

          {/* Wishlist Button */}
          <motion.button
            whileTap={{ scale: 1.25 }}
            onClick={handleWishlistToggle}
            className={`w-8 h-8 rounded-full bg-white/90 backdrop-blur-md flex items-center justify-center transition-all pointer-events-auto shadow-sm ${
              isHeartPopping ? 'animate-heart-pop' : ''
            }`}
            aria-label="Save to wishlist"
          >
            <Heart 
              className={`w-4 h-4 transition-colors ${
                isSaved ? 'text-rose-500 fill-rose-500' : 'text-slate-600 hover:text-rose-500'
              }`} 
            />
          </motion.button>
        </div>

        {/* EcoScore Badge Float */}
        <div className="absolute bottom-3 left-3">
          <EcoScoreBadge 
            score={accommodation.calculatedEcoScore} 
            size="md" 
            isVerified={accommodation.sustainability.certificationStatus === 'verified'} 
          />
        </div>

        {/* Match Percentage Tag (if generated by recommendation engine) */}
        {recommendation && (
          <div className="absolute bottom-3 right-3 bg-gradient-to-r from-emerald-700 to-eco-dark text-white text-xs font-black px-2.5 py-1 rounded-xl shadow-sm flex items-center gap-1 border border-white/20">
            <Sparkles className="w-3.5 h-3.5 text-emerald-200" />
            <span>{recommendation.matchScore}% Match</span>
          </div>
        )}
      </div>

      {/* Card Content */}
      <div className="p-4 sm:p-5 flex-1 flex flex-col justify-between space-y-3">
        <div className="space-y-2">
          {/* Location & Rating */}
          <div className="flex items-center justify-between text-xs text-slate-500">
            <span className="flex items-center gap-1 font-semibold truncate text-slate-600">
              <MapPin className="w-3.5 h-3.5 text-eco-primary shrink-0" />
              {accommodation.location}, {accommodation.country}
            </span>
            <span className="flex items-center gap-1 font-black text-slate-800 bg-amber-50 px-2 py-0.5 rounded-md border border-amber-200/60">
              ★ {accommodation.rating} <span className="font-normal text-slate-400">({accommodation.review_count})</span>
            </span>
          </div>

          {/* Title */}
          <Link to={`/accommodation/${accommodation.id}`} className="block group/title">
            <h3 className="font-extrabold text-base text-slate-900 group-hover/title:text-eco-primary transition-colors line-clamp-1 flex items-center justify-between">
              <span>{accommodation.name}</span>
              <ArrowUpRight className="w-4 h-4 text-slate-300 opacity-0 group-hover/title:opacity-100 transition-opacity" />
            </h3>
          </Link>

          {/* Tagline */}
          <p className="text-xs text-slate-500 line-clamp-2 leading-relaxed font-medium">
            {accommodation.tagline}
          </p>

          {/* Explainable Recommendation Match Reasons */}
          {recommendation && recommendation.matchReasons && recommendation.matchReasons.length > 0 && (
            <div className="bg-emerald-50/90 p-2.5 rounded-2xl border border-emerald-100/90 shadow-2xs">
              <p className="text-[11px] font-black text-eco-dark flex items-center gap-1 mb-1">
                <Sparkles className="w-3 h-3 text-eco-primary" /> Why Recommended:
              </p>
              <ul className="text-[11px] text-slate-700 space-y-1">
                {recommendation.matchReasons.slice(0, 2).map((reason, idx) => (
                  <li key={idx} className="flex items-start gap-1 font-medium">
                    <Check className="w-3.5 h-3.5 text-eco-primary shrink-0 mt-0.5" />
                    <span className="truncate">{reason}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Amenity tags preview */}
          <div className="flex flex-wrap gap-1.5 pt-1">
            {accommodation.amenities.slice(0, 3).map((amenity, idx) => (
              <span key={idx} className="text-[10px] font-bold bg-slate-100 text-slate-600 px-2 py-0.5 rounded-md">
                {amenity}
              </span>
            ))}
            {accommodation.amenities.length > 3 && (
              <span className="text-[10px] font-bold text-slate-400 px-1 py-0.5">
                +{accommodation.amenities.length - 3}
              </span>
            )}
          </div>
        </div>

        {/* Footer info: Guests, Price in INR & Compare Checkbox */}
        <div className="pt-3 border-t border-slate-100 flex items-center justify-between">
          <div className="flex flex-col">
            <span className="text-[10px] text-slate-400 font-bold uppercase tracking-wider">From</span>
            <div className="flex items-baseline gap-1">
              <span className="text-base font-black text-slate-900">₹{accommodation.price_per_night.toLocaleString('en-IN')}</span>
              <span className="text-xs text-slate-500">/ night</span>
            </div>
          </div>

          <div className="flex items-center gap-2">
            {/* Compare Selector Checkbox */}
            <motion.button
              whileTap={{ scale: 0.95 }}
              onClick={handleCompareToggle}
              className={`flex items-center gap-1 text-xs font-bold px-2.5 py-1.5 rounded-xl border transition-all ${
                compared 
                  ? 'bg-amber-100 text-amber-900 border-amber-300 shadow-2xs' 
                  : 'bg-slate-50 text-slate-600 border-slate-200 hover:bg-slate-100'
              }`}
            >
              <Layers className="w-3.5 h-3.5 text-amber-700" />
              <span>{compared ? 'Comparing' : 'Compare'}</span>
            </motion.button>

            {/* View Details Link */}
            <Link
              to={`/accommodation/${accommodation.id}`}
              className="bg-eco-primary hover:bg-eco-dark text-white text-xs font-bold px-3.5 py-1.5 rounded-xl transition-all shadow-xs hover:scale-102 flex items-center gap-1"
            >
              <span>View</span>
            </Link>
          </div>
        </div>

      </div>
    </motion.div>
  );
};
